#ifndef CONFIG_H
#define CONFIG_H

#define POWER_MANAGER_INPUT_PROFILE_USB_BENCH 1
#define POWER_MANAGER_INPUT_PROFILE_SOLAR35W 2
#define POWER_MANAGER_INPUT_PROFILE_AUTO 3

#ifndef POWER_MANAGER_INPUT_PROFILE
#define POWER_MANAGER_INPUT_PROFILE POWER_MANAGER_INPUT_PROFILE_USB_BENCH
#endif

#ifndef VERBOSE_SYSTEM_LOGS
#define VERBOSE_SYSTEM_LOGS 0
#endif

#endif