#ifndef CONFIG_H
#define CONFIG_H

#ifndef NODE_FIRMWARE_RELEASE
#define NODE_FIRMWARE_RELEASE 26
#endif

#ifndef NODE_FIRMWARE_RELEASE_LABEL
#define NODE_FIRMWARE_RELEASE_LABEL "v26.00"
#endif

#define POWER_MANAGER_INPUT_PROFILE_USB_BENCH 1
#define POWER_MANAGER_INPUT_PROFILE_SOLAR35W 2
#define POWER_MANAGER_INPUT_PROFILE_AUTO 3

#ifndef POWER_MANAGER_INPUT_PROFILE
#define POWER_MANAGER_INPUT_PROFILE POWER_MANAGER_INPUT_PROFILE_USB_BENCH
#endif

#ifndef VERBOSE_SYSTEM_LOGS
#define VERBOSE_SYSTEM_LOGS 0
#endif

#ifndef FIELD_DEBUG_BUILD
#define FIELD_DEBUG_BUILD 0
#endif

#ifndef ENABLE_BORON_USB_SOURCE_OVERRIDE
#define ENABLE_BORON_USB_SOURCE_OVERRIDE 1
#endif

#endif